### PR TITLE
Update danoni_constants.js

### PR DESCRIPTION
**Pull request by lvenier**
## :hammer:Details of Changes
 
Adding the default height on canvas-frame

## :bookmark: Related Issues, Reason for Changes

I believe fullscreen window gives a better look.

Up to you to decide if it makes sense.

### CODE REVIEW

**Comment by cwtickle** [comment]
Thank you for pull request!
The height of the "canvas-frame" is variable, but since the layout was not originally designed for full screen, this change is not applicable.

**Comment by lvenier** [comment]
you may still consider to add 
$id(`canvas-frame`).height = `${g_sHeight}px`;

if you want the "canvas-frame" height to be varable...

thanks for your reply and continue the good work.

**Comment by cwtickle** [comment]
Thanks for reply!
I think the following part could be changed.
```js
$id(`canvas-frame`).height = `${g_sHeight}px`;
```
But if that code is changed, I also think the following part could be changed in `danoni_main.css`.
This is because the height of 500px is currently defined on the css side for "canvas-frame".
```css
#canvas-frame {
        height: 500px;    /* <- this part */
	position: relative;
	overflow: hidden;
	white-space: nowrap;
}
```
Alternatively, you could use a CSS custom property to specify the following and then link it to `g_sHeight`.
In the example below, we ask the user to specify `--main-height-x` to determine the height.
```css
#canvas-frame {
	height: calc(var(--main-height-x, 500) * 1px);
	position: relative;
	overflow: hidden;
	white-space: nowrap;
}
```

**Comment by lvenier** [comment]
I believe people (me for instance) feel safer to add a style in canvas-frame than adding a css :)

**Pull request closed without merging**
