### PR TITLE
dospath external url

### PR DESCRIPTION
**Pull request by lvenier**
## :hammer: 変更内容 / Details of Changes

Adding a dospath query variable to fetch daa from external url

## :bookmark: 関連Issue, 変更理由 / Related Issues, Reason for Changes

To simplify danoni plus upgrade I would love to have data from external web service.
Upgrading the code is then possible with deployment as data is external

for instance : http://localhost:8080/danoni/danoni0.html?dos=hello.txt&dospath=https://localhost:8081/

## :pencil: その他コメント / Other Comments

if that PR idea is approved I believe similar things should be done for : songs, settings, customs, skins.... :)

### CODE REVIEW

**Comment by lvenier** [comment]
I am making a change to test a fix.

on chrome if I deploy the code I have the following error : 
```
danoni:1 Refused to execute script from 'https://toto.titi/danoni/dos/0001_ThrustUp.txt?1694415559700' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

text file can not be execute with newest security policies. The fix is to rename the dos file from txt to js to correct.

**Comment by cwtickle** [comment]
Thanks for PR!

> text file can not be execute with newest security policies. The fix is to rename the dos file from txt to js to correct.
That's true. But that specification is not compatible for current version...
Some people uses text file as a js file when they put their charts.
For the time being, if there is no extension in "dos" setting, it should be treated as if there is ".txt".

I think "dosPath" is a good idea. It could be used when you want to do a different chart or setting on a test basis.

**Comment by lvenier** [comment]
Thanks for your feedback
> 
> > text file can not be execute with newest security policies. The fix is to rename the dos file from txt to js to correct.
> 
I see 2 ways to implement this : you check if there is a file extension in the dos name query string. 
But my prefered version solution would be to add a variable in danoni_setting.js : 
dos_extension="txt" as default.
People can then overide the settings and change to js : 
dos_extension="js" 
It looks more flexible and less exposed to regression for existing deployed solution.

**Comment by cwtickle** [comment]
Thanks for comment.

Hmm... in that case, I think both are needed.
This is because it is difficult to make changes all at once when there are many files.

1. If there is no extension in "dos" setting, it should be treated as if there is ".txt".
2. If there is a file extension setting in danoni_setting.js (e.g. g_presetObj.dosExtension), the file name is added that extension.

If both 1 and 2 are satisfied, priority is given to 1.

**Comment by lvenier** [comment]
Do you want me to update the PR or do you prefer to take care of it yourself ?

**Pull request closed without merging**
